### ISSUE TITLE
Incorrect links to templates

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/docs-designing-interfaces#1]
When I click the links for the templates in the Lo-Fi design section I get a 404.

<img width="887" alt="screenshot 2015-10-20 13 48 35" src="https://cloud.githubusercontent.com/assets/3229463/10616083/5cce8bdc-7731-11e5-9e6d-8786084f5611.png">

**Comment by samclaridge** [comment]
This is fixed now :)

**Comment by samclaridge** [comment]
here's the fix https://github.com/NewSpring/docs-designing-interfaces/commit/7dbcaa6f380ca31cab6f4a5c22567009975e9e0a
